# Site settings
title: William M. Orr
email: wotech4@live.com
description: 'Portfolio of William M. Orr - Director of IT | IT Manager | IT Field Ops Manager'
author: William M. Orr
baseurl: "/Personal-Profile" # Project site subpath
url: "https://worr.com" # the base hostname & protocol for your site

twitter_username: wmorr
github_username: williammorr

# Navigation
brand_name: William M. Orr

# Hero/Header Section
hero:
  heading: William M. Orr – IT Leadership Portfolio
  description: Skilled IT leader with 12+ years of experience driving enterprise IT strategy, field operations, acquisitions, and infrastructure standardization across the U.S., Canada, and Puerto Rico. Proven success in delivering secure, scalable solutions that reduce costs and improve efficiency.
  button_text: View My Work
  button_link: "#portfolio"

# Call to Action Section
cta:
  heading: Driving IT Transformation & Operational Excellence
  description: From capital construction and large-scale acquisitions to Cisco network standardization and VoIP migrations, I deliver innovative IT strategies that align with business growth and reduce costs. Explore my portfolio to see how I’ve led organizations through complex transitions.
  button_text: Learn More
  button_link: "#services"

# Services Section
services:
  heading: Core Competencies
  list:
    - icon: fa-diamond
      title: IT Strategy & Leadership
      description: Over a decade of experience aligning IT strategy with sustainable business growth, managing multimillion-dollar budgets, and directing cross-functional teams.
      delay: 0
    - icon: fa-paper-plane
      title: Network & VoIP Standardization
      description: Led U.S., Canada, and Puerto Rico infrastructure conversions to Cisco-based systems and SIP VoIP, delivering $10M in telecom savings.
      delay: .1s
    - icon: fa-newspaper
      title: Capital Construction & Acquisitions
      description: Managed 2,500+ IT standardization projects, 100+ acquisitions, and enterprise construction initiatives including cost analysis, supplier negotiations, and ISP provisioning.
      delay: .2s
    - icon: fa-heart
      title: Team Development
      description: Built and mentored high-performing IT teams, ensuring on-time delivery, process improvements, and standardized support for thousands of locations.
      delay: .3s

# Portfolio Section
portfolio:
  - image: img/portfolio/1.jpg
    category: Enterprise IT
    name: SCI – Senior IT Manager / Interim Director
    link: "#"
  - image: img/portfolio/2.jpg
    category: IT Field Ops
    name: SCI – IT Manager & Field Ops Manager
    link: "#"
  - image: img/portfolio/3.jpg
    category: Infrastructure Projects
    name: 2,500+ Network & VoIP Standardization Projects
    link: "#"
  - image: img/portfolio/4.jpg
    category: Mergers & Acquisitions
    name: Integration of 100+ Acquisitions
    link: "#"
  - image: img/portfolio/5.jpg
    category: Vendor & ISP Negotiations
    name: Telecom & ISP Contracting with $10M Savings
    link: "#"
  - image: img/portfolio/6.jpg
    category: Field Services Leadership
    name: Meriplex – Field Services Manager & Project Manager
    link: "#"

# Aside Section
aside:
  heading: Explore My Full Portfolio & References
  button_text: Visit My Website
  button_link: "https://worr.com"

# Contact Section
contact:
  heading: Let’s Get In Touch!
  description: Interested in IT leadership, infrastructure transformation, or strategic consulting? Reach out by email or phone, or connect via my website. I’ll get back to you as soon as possible.

# Build settings
markdown: kramdown
